name: test

on: [push]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --verbose
      
      - name: Run tests
        run: cargo test --verbose

      - name: Run test driver
        run: |
            cd c_runtime
            ./run_tests.py
