name: test

on: [push]
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rust-src, rustfmt, clippy

      - name: Build
        run: cargo build --verbose
      
      - name: Run tests
        run: cargo test --verbose

      - name: Run test driver
        run: |
            cd c_runtime
            ./run_tests.py
